language: c

sudo: false

addons:
    apt:
        packages:
            - gfortran

env:
    global:
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='click numpy cython jinja2 matplotlib mkl'
        - SETUP_XVFB=True
    matrix:
        - PYTHON_VERSION=2.7 REQUIREMENTS_FILE=requirements.txt
        # - PYTHON_VERSION=3.6 REQUIREMENTS_FILE=requirements_python3.txt

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install -r $REQUIREMENTS_FILE

script:

    - ./make.py --help
    - ./make.py tool-info

    - ./make.py make_observer_table
    - ./make.py make_skycoord_table
    - ./make.py benchmark_celestial
    - ./make.py benchmark_horizontal
    - ./make.py summary_celestial

    # Making all plots is slow, but this is run rarely enough that it's fine to just do them all. However,
    # if you are debugging, you could instead add the --tools=astropy flag to generate just some of the
    # plots.
    - ./make.py plots

    # If on master, we deploy the results (only for one Python version)
    - if [[ $PYTHON_VERSION == 2.7 && $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == "master" ]]; then
        git config --global user.name "astropy-bot";
        git config --global user.email "astropy.team@gmail.com";
        openssl aes-256-cbc -K $encrypted_ae4bff0a7007_key -iv $encrypted_ae4bff0a7007_iv -in github_deploy_key.enc -out ~/.ssh/publish-key -d;
        chmod u=rw,og= ~/.ssh/publish-key;
        echo "Host github.com" >> ~/.ssh/config;
        echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config;
        ./make.py deploy --repo=astropy/coordinates-benchmark;
      fi
